### ISSUE TITLE
Gradle

### ISSUE THREAD

**Issue by deckameron** [AppWerft/Titanium-AndroidStudio#2]
Hi @AppWerft ,

Thank you for the tutorial!
Is it possible to use Gradle with this setup? If so, how?

**Comment by drauggres** [comment]
Hi @deckameron.

Currenty gradle is not supported by Titanium in any way.
I've tried to make simple [gradle-wrapper around ti-cli](https://github.com/drauggres/ti.gradle.fake), but it's not as good as I expected (android studio fails to track git changes for files by symlink).
It works better if you swap symlinks and real directories (so real code will be in gradle structure and in Titanium side will stay the symlink), but this will probably create problem for TiStudio users.

**Comment by deckameron** [comment]
I see! Thank you very much for your help.
I will give ti.gradle.fake a try. :)
